fix h36 enqueue operation to accept policies for prospective year
ideacrew/fdsh_gateway pull request #167
Opened 2023-10-09 21:32 UTC by saipraveen18

https://www.pivotaltracker.com/story/show/186215618

2023-10-09 22:38 UTC, saikumar9 requested changes

2023-10-09 22:38 UTC, saikumar9 commented on app/event_source/subscribers/fdsh/insurance_policies/posted_subscriber.rb
> +          result
@ saipraveen18 We don't need to return the result from this method as it is not being used. So you can remove lines 70, 67, and 63 and remove the assignment in line 60.

2023-10-09 22:38 UTC, saikumar9 commented on spec/event_source/subscribers/fdsh/insurance_policies/posted_subscriber_spec.rb
> +    context "prospective assistance_year" do
Also, can you update the tests to verify the creation of the transaction(for the given policy) for the expected transmission for the cases where the insurance policy is for the past year, current year, and prospective year?

2023-10-10 15:01 UTC, saikumar9 approved these changes
lgtm!

2023-10-10 16:53 UTC, vkghub approved these changes
LGTM

2023-10-10 16:53 UTC, merged